[package]
name = "pacifica"
version = "0.1.0"
edition = "2024"

[dependencies]
base58 = "0.2.0"
ed25519-dalek = "2.2.0"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
